### ISSUE TITLE
Complex query with invalid resource id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#158]
@when('The complex query resource id is invalid')
def step_impl(context):

    payload = {
        "id": generate_random_chars()+".public",--> Getting response 200
        "attribute": {
            "term": "speed",
            "min": 30,
            "max": 50
        },

**Comment by pct960** [comment]
Fixed in https://github.com/datasetu/vermillion/pull/156/commits/6577d47a5bd7a1c4bd9f783a095b70a7b0521581
