### ISSUE TITLE
Geo-spatial query with invalid resource id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#159]
@when('The geospatial query resource id is invalid')
def step_impl(context):
    payload = {
        "id": generate_random_chars()+".public",--> Response 200
        "geo_distance": {
            "coordinates": [82.9739, 25.3176],
            "distance": "10000m"
        }
    }

**Comment by pct960** [comment]
Fixed in https://github.com/datasetu/vermillion/pull/156/commits/6577d47a5bd7a1c4bd9f783a095b70a7b0521581
