### ISSUE TITLE
Timeseries query for invalid resource id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#160]
@when('Timeseries query resource id is invalid')
def step_impl(context):

    payload = {
        "id": generate_random_chars()+".public",--> Response 200
        "time": {
            "start": "2020-03-01",
            "end": "2020-03-27"
        }
    }

**Comment by pct960** [comment]
Fixed in https://github.com/datasetu/vermillion/pull/156/commits/6577d47a5bd7a1c4bd9f783a095b70a7b0521581
