### ISSUE TITLE
Attribute value query with empty term value

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#168]
payload = {
        "id":
            "rbccps.org/aa9d66a000d94a78895de8d4c0b3a67f3450e531/rs.varanasi.iudx.org.in/varanasi-swm-vehicles/varanasi-swm-vehicles-live.public",
        "attribute": {
            "term": "",--> **Gets a 200 response. Is that valid**?
            "min": 30,
            "max": 50
        }

**Comment by pct960** [comment]
Fixed.
