### ISSUE TITLE
Handling Consumer token expiry - Implementation

### ISSUE THREAD

**Issue by Prabhu4452** [datasetu/vermillion#183]
When Consumer accesses the secure datasets, if token is said to be expired and then consumer needs to be restricted from accessing secure datasets.

Assumptions-
1) Consumer hits download API prior to Consumer API

**Comment by Prabhu4452** [comment]
As the dev is complete, moving into testing for further testing of code.

**Comment by vasanth096** [comment]
Testing is complete. Works fine
