### ISSUE TITLE
Scroll api- Getting 500 response when queried same request again

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#208]
![image](https://user-images.githubusercontent.com/69444787/114126887-e8dc1600-9916-11eb-8b9d-b6b10d45b5a8.png)
Steps to reproduce:
* Get the scroll id from the search request of a public geospatial query
* In the search/scroll api, pass the scroll id and duration
* Generate a token and pass it as a param and send the request
* There is a 200 ok response.
* When the same request is fired again, its giving a 500 as show in image.

**Comment by Gtgstg** [comment]
Fixed in #228
