### ISSUE TITLE
Scroll api- The query gets 200 response when passed with a token and invalid resource id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#209]
![image](https://user-images.githubusercontent.com/69444787/114130681-b9310c00-991e-11eb-8ed1-dafcefc46e17.png)
Steps to reproduce:
* Fetch the scroll id from the search api of open geospatial query
* Pass the srcoll id and duration in the request of the search/scroll api
* Generate a token for res_ids( rbccps/..../test-resource1,2,3, .public)
* Pass that token and an invalid resource id as shown in image
* Expected output is 400 but gets 200.

**Comment by pct960** [comment]
The scroll ID is generated only after a successful search request is made. Therefore, the scroll API does not read the resource ID and hence has no bearing on the functioning of the API. Going forward, we could throw bad requests for unnecessary params and keys in the body. Currently, the API simply ignores extra params. Will re-open when handling this becomes a priority.
