### ISSUE TITLE
Scroll search- Getting 403 unauthorised error when requested for a public id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#224]
![image](https://user-images.githubusercontent.com/69444787/114342049-b893b200-9b78-11eb-80b0-da0e6687f129.png)
Steps to reproduce:
* Generate a scroll id for a public resource for a search api
* Pass the scroll id and duration for the search/scroll api
* Pass an unauthorised id as a param and send the request
* Generates a 403 unauthorised error but ideally has to be 200 since we are requesting for a public resource

**Comment by pct960** [comment]
If you are requesting a public resource then there is no need for passing a token. However, if a token is passed, whether for a public or secure resource then its validity is checked. So if it's an invalid token, the API will not proceed to query the db.
