### ISSUE TITLE
Scroll search- Getting a 200 response when queried for a secured resource without a token

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#226]
![image](https://user-images.githubusercontent.com/69444787/114493791-cc9ee880-9c38-11eb-8475-169c26a8749a.png)
Steps to reproduce:
* Set policy and request token for a secured resource
* Pass the token and id along with scroll duration and size in the search api
* Get the scroll id and pass that in the search/scroll api without passing the token
* Responds with a 200. Ideally it should be asking for the token and respond with 400.

**Comment by pct960** [comment]
The scroll API does not know beforehand if the scroll ID's search context contains public or secure resources. The way this is tackled is that when the results come back from a scrolled search, every resource ID is checked against a set of authorised IDs for inclusion in the result set. If the resource ID is neither public nor contained in the authorised ID set, the data object is not added to the result set. That is why, although the response is 200, the result set is empty.
