### ISSUE TITLE
Scroll api- Getting 200 response if slight editing is made with the scroll id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#227]
![image](https://user-images.githubusercontent.com/69444787/114495746-408ec000-9c3c-11eb-892b-fecb5d8a15fe.png)
Steps to reproduce:
* Get a scroll id from the search api and pass it in the search/scroll api
* Edit the scroll id in the search/scroll api by removing the "==" and the last character of the id(which ends with 'w') and replace with 'x', 'y' or 'z'.
* Still the api passes with 200
![image](https://user-images.githubusercontent.com/69444787/114495977-af6c1900-9c3c-11eb-8dcc-d5d55905a1d3.png)

**Comment by pct960** [comment]
Partly fixed in #228. If it is a valid base64 encoding, then there is no way to know if it's a valid scroll ID without contacting ES. However, basic checks are implemented in #228
