### ISSUE TITLE
Scroll api- Variation in the results when queried with a change in duration

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#231]
This is the initial search request
![image](https://user-images.githubusercontent.com/69444787/114668732-afdce080-9d1e-11eb-91dd-d494d9671f17.png)
First scroll search request with duration as 2s getting 200
![image](https://user-images.githubusercontent.com/69444787/114668799-c5eaa100-9d1e-11eb-8f5b-3a1b34737668.png)
Same request queried by changing duration to 5s getting 400
![image](https://user-images.githubusercontent.com/69444787/114668874-dc90f800-9d1e-11eb-9b86-8701fe1267f1.png)

**Comment by pct960** [comment]
This is not an issue. The scroll ID has expired. Try for a longer duration
