### ISSUE TITLE
Scroll search- Getting a 500 response for a used scroll id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#236]
![image](https://user-images.githubusercontent.com/69444787/114814503-f17a9380-9dd1-11eb-8bc6-5d29be63eb07.png)
Steps to reproduce:
* Generate a scroll id from the search api and copy the scroll id.
* Do a ./install and use that copied scroll id and query the scroll search api.
* Gives a 500 response

**Comment by pct960** [comment]
This is expected behaviour and not a bug. When you pass a stale scroll ID to a freshly installed instance of vermillion, there is neither any data in the indices nor any search context for the scroll. Therefore, this happens. We will add a rate limiter to prevent repeated requested like this.
