### ISSUE TITLE
Scroll search- Scroll id expiry is getting delayed

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#237]
The scroll id takes longer time to expire than whats mentioned in the scroll duration.
For ex: If the scroll_duration is given as 1s, its taking close to 15-20 seconds to expire.

**Comment by pct960** [comment]
We plan to have a mechanism in place to limit any scrolled search to a maximum of 1 hour. So before that happens, we will have to honour how elasticsearch handles expiry for scrolled searches. It appears that there is a small window between the expected expiry time and the actual. So this is how es internally handles expirations. This issue will persist until we implement the mechanism described earlier
