### ISSUE TITLE
Scroll api- The hits response is empty when the same request is sent more than twice

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#241]
![image](https://user-images.githubusercontent.com/69444787/115655252-880a0000-a350-11eb-97b3-27d72f6f5205.png)
Steps to reproduce:
* Get the scroll id and pass it in the scroll api
* We get the expected response when queried the same twice and beyond that it gives an empty response.

**Comment by pct960** [comment]
This is not a bug. If the responses have been exhausted when the scroll API is called, subsequent scroll API calls will yield empty results.
