### ISSUE TITLE
Search api- Generates invalid scroll id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#242]
![image](https://user-images.githubusercontent.com/69444787/115656089-29de1c80-a352-11eb-933e-5d1b304703e3.png)
Search end point generates the scroll id with a '-'
![image](https://user-images.githubusercontent.com/69444787/115656150-48dcae80-a352-11eb-8880-92f665b2766c.png)
When passed that id in the scroll api- gives a response of invalid scroll id

**Comment by pct960** [comment]
It's hard to check if a scroll ID is valid. One way to solve this would be to handle all scroll IDs internally. Temporarily removed scroll ID checks in #254. Will implement a combined search & scroll API in an upcoming PR
