### ISSUE TITLE
Search api- Having size attribute without scroll duration still gives default output

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#250]
![image](https://user-images.githubusercontent.com/69444787/116028153-23161900-a674-11eb-9d42-570d1fd8b1c1.png)
* There needs to be a condition that size can be added only if the scroll duration is specified, else it is meaningless.

**Comment by pct960** [comment]
If somebody wants to test their query construction but not get the full result set then the size parameter is useful.
