### ISSUE TITLE
Latest api- Getting 403 for public resource id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#251]
![image](https://user-images.githubusercontent.com/69444787/116038334-f6b7c800-a686-11eb-90ba-87bdcc28db1a.png)
* Let the token authentication happen only for secured id's

**Comment by pct960** [comment]
Fixed in #254

**Comment by vasanth096** [comment]
Its accepting any token for 32 char size but if given other than that it says malformed token. Eventhough both are invalid tokens but the result varies. Can't we just ignore the token part on public id's?

**Comment by pct960** [comment]
This is a very minor issue as the token is anyway ignored in the case of public IDs. If the token check should not be done then the user should not pass a token for public resource IDs. However, we can move around the logic a bit to allow for this.

**Comment by pct960** [comment]
Fixed in https://github.com/datasetu/vermillion/commit/3063689a4d2f972f7cf6ac3ee88c3ccb2db551b6
