### ISSUE TITLE
Publish api- Files are getting uploaded and not moved/deleted

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#253]
![image](https://user-images.githubusercontent.com/69444787/116188025-44ded100-a744-11eb-9a31-f34f9bff4776.png)
* This happens to test cases having:
     *  Empty resource id
     * Empty token
     * Invalid resource id
     * Invalid token
     * Invalid json meta file
     * Without resource id
     * Without token

**Comment by pct960** [comment]
Fixed in #254

**Comment by vasanth096** [comment]
The problem still exists

**Comment by pct960** [comment]
Fixed in https://github.com/datasetu/vermillion/commit/f21aa0220d8d099f9c9a50447d7c97c0ba329686

**Comment by vasanth096** [comment]
This problem exits for file uploads greater than 2.

**Comment by Prabhu4452** [comment]
@vasanth096
I have made the necessary changes for the fix. Please go ahead and test.

**Comment by vasanth096** [comment]
Tested. Its issue is fixed.

**Comment by vasanth096** [comment]
This issue again came up while testing for Token Expiry. Please check.
Steps to reproduce:
1. Set a policy for a resource id for 10 secs and fetch a token for the same.
2. Change the token or create an error in the request and send the request
3. The files are getting uploaded and not getting deleted.

**Comment by vasanth096** [comment]
Works fine
