### ISSUE TITLE
Publish api- Secured resource id with invalid token is getting passed with 202

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#255]
![image](https://user-images.githubusercontent.com/69444787/116379517-b4ca8580-a830-11eb-8eb3-b8376fc83f2d.png)
![image](https://user-images.githubusercontent.com/69444787/116379549-bc8a2a00-a830-11eb-9d83-f4447788bd6e.png)

**Comment by pct960** [comment]
The auth check is done by the broker backend. So, this is not an issue.
