### ISSUE TITLE
Downloadbyquery api- Getting 202 status if the query parameter is invalid

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#303]
![image](https://user-images.githubusercontent.com/69444787/133070174-b5ca5eb7-ac81-4650-9898-756d935c314b.png)

**Comment by Prabhu4452** [comment]
@vasanth096 
Can you please validate this agin with latest changes being pushed with below commit id and let me know if this still persists.
If so, will look into this again.
commit id - 335ccde09bfd92fa3f32ceb9bbeafe1bbfee2732

**Comment by vasanth096** [comment]
Validated the same and it works fine.
