### ISSUE TITLE
Token expiry- Gets a 200 response for an expired token

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#307]
![image](https://user-images.githubusercontent.com/69444787/135390372-e4c39d13-3b90-4030-b96e-1096c6c98aed.png)

Steps to recreate:

1. Set a policy for 20 secs.
2. Request a token for that id
3. Publish for that id
4. Hit the download api endpoint after 20 secs.

**Comment by vasanth096** [comment]
Consumer end point
![image](https://user-images.githubusercontent.com/69444787/135391619-f94c832b-80ba-49d2-ae99-56b00baaa78e.png)

**Comment by Prabhu4452** [comment]
Hello @vasanth096 
The issue is now fixed. Could you please validate the latest changes against the below commit id.
id- fc208e912c4bfb01c9357e041b060904a5ab07e6

**Comment by vasanth096** [comment]
Works fine
