### ISSUE TITLE
ProviderByQuery api- Email not validating

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#311]
![image](https://user-images.githubusercontent.com/69444787/140885120-0f78e012-bfa8-460a-ad5e-91694dc2c1eb.png)

Can we have some sort of validation to the given email id ?

**Comment by Prabhu4452** [comment]
@vasanth096 
Yes, the email validation is taken care against below commit id.
id = efd110e71047fefec5f042b4766ee86af907b481
Please validate the changes.

**Comment by vasanth096** [comment]
Works fine. Closing the issue
