### ISSUE TITLE
ProviderByQuery- Getting same file even if other files are published

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#316]
Steps to Reproduce:

1. Set a policy and request a token for a resource id
2. Publish sample file with a meta file for that id.
3. Publish a different file with the same meta file and hit the Provider by Query API for the same id in step2.
4. The downloaded file is the file that is published on step 2.
5. Ideally both the files have to be downloaded.

**Comment by Prabhu4452** [comment]
The development for this fix is ready. Please go ahead and test it out.

**Comment by vasanth096** [comment]
@Prabhu4452  Getting the same even after testing. Please check

**Comment by vasanth096** [comment]
Works as expected
