### ISSUE TITLE
Download public datasets as a zip file - API | Implementation

### ISSUE THREAD

**Issue by Prabhu4452** [datasetu/vermillion#324]
Requirement:
Implement a new API which should provide capability for a data consumer to download public datasets as a zip file based on the search query parameters that a data consumer provides as part of the API. To add more, the API should send a notification as an email to data consumer with the downloadable link of the datasets.

Key Points:

At least one search query parameter is needed.
Resource Id could be an optional parameter.
Sample API endpoint structure:
https://vermillion.datasetu.org/API_Name?token=sample_token&id=sample_id&gender=male

Sample output:
An email to the data consumer with following content.

Subject: Download Links
Content:
Dear consumer,
The downloadable links for the datasets you requested are ready to be served. Please use below link to download the datasets as a zip file.
Sample downloadable link:
https://vermillion.datasetu.org/provider/public/uuid/filename.zip

**Comment by vasanth096** [comment]
Testing is complete. Api is implemented.
